version: '3.9'
services:
  yolo-mongo-db:
    image: mongo:5.0.16
    environment:
      MONGO_DATABASE: yolomy
    ports:
      - 27017:27017
  yolo-web-client:
    image: ibrahimabdike/yolo-client-image:v1
    environment:
      PORT: 3000
      PROXY_API: http://yolo-web-backend:5000/
    ports:
      - 3000:3000
    